# ══════════════════════════════════════════════════════════════════════
# Snakefile — Metagenomic + Virome Pipeline
#
# PIPELINE OVERVIEW:
#   FASTQs
#     └─► fastp / NanoPlot+Porechop+Filtlong (QC + trimming)
#           └─► [host removal — optional] bwa-mem2 / minimap2
#                 └─► MEGAHIT / Flye (ONT) or metaMDBG (HiFi) (assembly)
#                 └─► Merge + filter + MMseqs2 (deduplication)
#                       ├─► QUAST (assembly quality)
#                       ├─► Viral detection ──► CheckV ──► vRhyme
#                       │     VirSorter2, GeNomad
#                       │
#                       └─► BWA-MEM2 / minimap2 (read mapping → contigs)
#                                 └─► depth.txt (coverage per contig)
#                                       └─► MetaBAT2, SemiBin2
#                                                 └─► Binette
#                                                       └─► CheckM2
#                                                             └─► GTDB-Tk
#                                                                   └─► HTML Report
#
# HOW TO RUN:
#   snakemake -n --use-conda --cores 32        # dry-run
#   snakemake --use-conda --cores 32           # run
#   snakemake --dag | dot -Tsvg > dag.svg      # visualise DAG
#
# MODULES (rules/):
#   qc.smk              — BLOCK 1  : fastp, NanoPlot, Porechop, Filtlong
#   host_removal.smk    — BLOCK 1.5: bwa-mem2/minimap2 host decontamination (optional)
#   assembly.smk        — BLOCK 2  : MEGAHIT, Flye + Medaka (ONT), metaMDBG (HiFi)
#                          -- the assembly is the hub (item (d)): no merge, no dedup
#   quast.smk           — BLOCK 4  : QUAST
#   viral_detection.smk — BLOCK 5  : VS2, GeNomad, viral_consensus
#   mapping.smk         — BLOCK 6  : BWA-MEM2, minimap2, calc_depth
#   cobra.smk           — BLOCK 5.5: COBRA contig extension (optional, SR PE only)
#   viral_binning.smk   — BLOCK 7  : vRhyme, CheckV (×2)
#   prok_binning.smk    — BLOCK 8  : MetaBAT2, SemiBin2, Binette, CheckM2, GTDB-Tk
#   taxonomy.smk        — BLOCK 9  : prodigal-gv, MMseqs2 taxonomy, viral_taxonomy
#   host_prediction.smk — BLOCK 10 : PHIST
#   defense_amr.smk     — BLOCK 10.5: DefenseFinder, AMRFinderPlus, RGI/CARD, DeepARG, ABRicate, argNorm
#   finalize.smk        — BLOCK 11 : organize_outputs
#   report.smk          — BLOCK 12/13: generate_report, MultiQC
# ══════════════════════════════════════════════════════════════════════

import os
import re
import yaml as _yaml
from pathlib import Path

PIPELINE_DIR = workflow.basedir
SCRIPTS_DIR  = os.path.join(PIPELINE_DIR, "scripts")

import sys as _sys
_sys.path.insert(0, PIPELINE_DIR)
from pipeline_config import resolve_pipeline_config, validate_pipeline_config

# ── Container URIs ─────────────────────────────────────────────────────
# Loaded from containers.lock.yaml (generated by scripts/pin_containers.py).
# If the lock file is absent, all container: directives resolve to None and
# Snakemake silently falls back to --use-conda.
_LOCK = os.path.join(PIPELINE_DIR, "containers.lock.yaml")
if os.path.exists(_LOCK):
    CONTAINERS = _yaml.safe_load(open(_LOCK)) or {}
else:
    CONTAINERS = {}


# ══════════════════════════════════════════════════════════════════════
#  CONFIGURATION — loaded from config.yaml
#
#  Edit config.yaml (in your working directory) before running.
#  Run via the VAPOR CLI:
#    vapor --dry-run              # validate
#    vapor --threads 32           # execute
#    vapor --config my.yaml       # custom config path
#    vapor -h                     # full help
#
#  Or directly with Snakemake (must pass --configfile explicitly):
#    snakemake --use-conda --cores 32 --configfile config.yaml
# ══════════════════════════════════════════════════════════════════════

configfile: "config.yaml"

# ── Map config dict → pipeline variables ──────────────────────────────
def _expand(p):
    """expanduser with fallback when $HOME is not set (some HPC environments)."""
    try:
        return str(Path(p).expanduser())
    except RuntimeError:
        return str(Path(p))

def write_status(done_path, status):
    """
    Write a rule's real outcome into its done.txt instead of touching it empty.

    Status is one line: 'ok', 'skipped: <reason>' or 'failed: <reason>'. An
    empty done.txt makes "the tool crashed" and "the tool found nothing"
    indistinguishable downstream, which is how a disk-full AMRFinderPlus run
    was read as a biological zero. The report's load_tool_status() consumes
    this, so a failed rule shows as a gap rather than a count of 0.
    """
    Path(done_path).parent.mkdir(parents=True, exist_ok=True)
    Path(done_path).write_text(str(status).strip() + "\n")

FASTQ_DIR            = _expand(config["fastq_dir"])
OUTDIR               = _expand(config["outdir"])
THREADS              = config["threads"]

MEGAHIT_MEM          = config["megahit_mem_gb"] * 1_000_000_000  # bytes
MEGAHIT_PRESET       = config["megahit_preset"]
MEGAHIT_CUSTOM_PARAMS = config["megahit_custom_params"]

MIN_CONTIG           = config["min_contig"]
VIRAL_MIN_CONTIG     = config["viral_min_contig"]

CHECKV_DB            = config["checkv_db"]
VS2_DB               = config["vs2_db"]
GENOMAD_DB           = config["genomad_db"]
CHECKM2_DB           = config["checkm2_db"]
INPHARED_DB          = config["inphared_db"]
GTDBTK_DB            = config["gtdbtk_db"]

CUSTOM_PROK_MMSEQS_DB  = _expand(config.get("custom_prok_mmseqs_db",  "")) if config.get("custom_prok_mmseqs_db",  "") else ""
CUSTOM_VIRAL_MMSEQS_DB = _expand(config.get("custom_viral_mmseqs_db", "")) if config.get("custom_viral_mmseqs_db", "") else ""

SEMIBIN_ENV          = config["semibin_env"]

MIN_VIRAL_TOOLS      = config["min_viral_tools"]
VIRAL_CONSENSUS_MODE = config["viral_consensus_mode"]
SCORE_VS2_MIN        = config["score_vs2_min"]
SCORE_GENOMAD_MIN    = config["score_genomad_min"]

LONG_READS           = config["long_reads"]
SINGLE_END           = config.get("single_end", False) and not LONG_READS
LR_TECH              = config["lr_tech"]
LR_MIN_LEN           = config["lr_min_len"]
LR_MIN_MEAN_Q        = config["lr_min_mean_q"]
LR_FLYE_OVERLAP      = config["lr_flye_overlap"]
LR_MEDAKA_MODEL      = config["lr_medaka_model"]
LR_ONT_CHEM          = config["lr_ont_chem"]

# ── Host genome removal (optional) ────────────────────────────────────
HOST_GENOME      = _expand(config.get("host_genome", "")) if config.get("host_genome", "") else ""
HOST_INDEX       = _expand(config.get("host_index",  "")) if config.get("host_index",  "") else ""
USE_HOST_REMOVAL = bool(HOST_GENOME)

def _clean_r1(wc):
    """R1 (or SE read) after optional host removal; falls back to fastp output."""
    if USE_HOST_REMOVAL:
        return f"{OUTDIR}/{wc.sample}/host_removed/{wc.sample}_R1_clean.fq.gz"
    return f"{OUTDIR}/{wc.sample}/trimmed/{wc.sample}_R1_fastp.fq.gz"

def _clean_r2(wc):
    """R2 after optional host removal. Returns [] for single-end mode."""
    if SINGLE_END:
        return []
    if USE_HOST_REMOVAL:
        return f"{OUTDIR}/{wc.sample}/host_removed/{wc.sample}_R2_clean.fq.gz"
    return f"{OUTDIR}/{wc.sample}/trimmed/{wc.sample}_R2_fastp.fq.gz"

def _clean_lr(wc):
    """LR input after optional host removal; falls back to filtlong output."""
    if USE_HOST_REMOVAL:
        return f"{OUTDIR}/{wc.sample}/host_removed/{wc.sample}_lr_clean.fastq.gz"
    return f"{OUTDIR}/{wc.sample}/lr_filtered/{wc.sample}_filtered.fastq.gz"

def _contigs_path(sample):
    """Assembly of one sample -- the central hub since item (d) of
    docs/ROADMAP_SIMPLIFICACAO.md: one assembler per track, no merge, no
    dedup. Mirrors the co-assembly track, which already points straight at
    the assembler output (`{OUTDIR}/coassembly/{group}/contigs.fa`).

    Takes a sample NAME, not a wildcards object, so `rule all` and
    coassembly.smk can call it too -- this decision tree must exist in
    exactly one place. Three copies of it were what the (d) review flagged
    as the thing most likely to drift apart later.
    """
    if LONG_READS:
        return (f"{OUTDIR}/{sample}/assembly/lr/flye_polished/assembly.fasta"
                if LR_TECH == "ont"
                else f"{OUTDIR}/{sample}/assembly/lr/metaMDBG/assembly.fasta")
    return f"{OUTDIR}/{sample}/assembly/megahit/final.contigs.fa"


def _sample_contigs(wc):
    """`_contigs_path` as a Snakemake input function."""
    return _contigs_path(wc.sample)

USE_GPU              = config.get("use_gpu", False)
COVERM_METHOD        = config.get("coverm_method", "rpkm")

PHAROKKA_DB               = config.get("pharokka_db", "")
PHOLD_DB                  = config.get("phold_db", "")
PHAROKKA_MIN_COMPLETENESS = config.get("pharokka_min_completeness", 90.0)
BAKTA_DB                  = config.get("bakta_db", "")
# Prokaryotic MAG quality gate for downstream annotation (Bakta), MIMAG
# Medium-quality by default (>=50% completeness, <=10% contamination). Lower
# `prok_min_completeness` for high-novelty / fragmented datasets (e.g.
# IonTorrent) where MAGs rarely reach MQ — analogous to `viral_min_quality`
# on the viral side. AMR / defense / GTDB-Tk are NOT gated (they already run
# on every bin). Legacy bakta_* keys still override the unified gate.
PROK_MIN_COMPLETENESS     = config.get("prok_min_completeness", 50.0)
PROK_MAX_CONTAMINATION    = config.get("prok_max_contamination", 10.0)
BAKTA_MIN_COMPLETENESS    = config.get("bakta_min_completeness", PROK_MIN_COMPLETENESS)
BAKTA_MAX_CONTAMINATION   = config.get("bakta_max_contamination", PROK_MAX_CONTAMINATION)
EGGNOG_DB                 = config.get("eggnog_db", "")

# ── Defense systems + AMR (prokaryotic bins) ───────────────────────────
DEFENSE_AMR_ENABLED          = config.get("use_defense_amr", True)
CARD_DB                      = _expand(config.get("card_db", "")) if config.get("card_db", "") else ""
DEEPARG_DB                   = _expand(config.get("deeparg_db", "")) if config.get("deeparg_db", "") else ""
DEFENSE_FINDER_MODELS_DB     = _expand(config.get("defense_finder_models_db", "")) if config.get("defense_finder_models_db", "") else ""
ABRICATE_ENABLED             = config.get("use_abricate", True)
ARGNORM_ENABLED              = config.get("use_argnorm", True)
DEFENSE_AMR_VIRAL_ENABLED    = config.get("use_defense_viral", True)
APIS_DB                      = _expand(config.get("apis_db", "")) if config.get("apis_db", "") else ""
AMR_CONSENSUS_ENABLED        = config.get("use_amr_consensus", True)
LOW_DEPTH_MODE              = config.get("low_depth_mode", False)


# ── Viral filtering for prokaryotic binning ────────────────────────────
PROK_FILTER_VIRAL = config.get("prok_filter_viral", True)
# Provirus-bearing contigs are always kept in prok binning (not configurable)

# ── GUNC chimera detection ─────────────────────────────────────────────
GUNC_ENABLED = config.get("use_gunc", True)
GUNC_DB      = _expand(config.get("gunc_db", "")) if config.get("gunc_db", "") else ""

# ── vOTU clustering (skani / ICTV) ─────────────────────────────────────
VOTU_CLUSTERING_ENABLED = config.get("use_votu", True)
VOTU_ANI                = config.get("votu_ani", 95.0)
VOTU_AF                 = config.get("votu_af", 85.0)

VOTU_PRESENCE_MIN_COV  = config.get("votu_presence_min_coverage", 75.0)

# BACPHLIP lifestyle (lytic/lysogenic) over vOTU representatives.
BACPHLIP_MIN_QUALITY         = config.get("bacphlip_min_quality", ["Complete", "High-quality"])
BACPHLIP_VIRULENCE_THRESHOLD = config.get("bacphlip_virulence_threshold", 0.5)

# eggNOG-mapper over viral ORFs from MQ+ vOTU representatives -> putative AMGs.
USE_EGGNOG_VIRAL = config.get("use_eggnog_viral", True)

# ONT reads carry a per-read error rate well above 5%, so the 95% identity
# filter used for Illumina/HiFi would reject nearly every ONT alignment and
# silently empty the presence matrix. Default per technology; overridable.
_recruit_id = config.get("votu_recruit_min_identity")
if _recruit_id is None:
    _recruit_id = 85 if (LONG_READS and LR_TECH == "ont") else 95
VOTU_RECRUIT_MIN_ID = _recruit_id

# ── MAG dereplication (galah) ──────────────────────────────────────────
MAG_DEREP_ENABLED = config.get("use_mag_derep", True)
MAG_DEREP_ANI     = config.get("mag_derep_ani", 95.0)

# ── COBRA viral contig extension ───────────────────────────────────────
COBRA_ENABLED      = config.get("use_cobra", False)
COBRA_MEGAHIT_MINK = config.get("cobra_megahit_mink", 21)
COBRA_MEGAHIT_MAXK = config.get("cobra_megahit_maxk", 141)

# ── Reads-only classification (Sylph) ─────────────────────────────────
READS_CLASSIFY_ENABLED = config.get("reads_classify", False)

# ── Pipeline tracks + co-assembly (resolved + validated) ──────────────
validate_pipeline_config(config)
_PCFG = resolve_pipeline_config(config)
TRACK_READS          = _PCFG["track_reads"]
TRACK_VIRAL          = _PCFG["track_viral"]
TRACK_PROK           = _PCFG["track_prok"]
USE_HOST_DEFENSE     = _PCFG["use_host_defense"]
INTEGRATION_ENABLED  = _PCFG["integration_enabled"]
COASSEMBLY_ENABLED   = _PCFG["coassembly_enabled"]
COASSEMBLY_GROUPING  = _PCFG["coassembly_grouping"]
COASSEMBLY_VIRAL     = _PCFG["coassembly_viral"]
COASSEMBLY_BINNING   = _PCFG["coassembly_binning"]
COBINNING_MULTISPLIT = _PCFG["cobinning_multisplit"]
# Minimum CheckV quality tier kept for the viral subset that feeds taxonomy /
# host prediction / annotation (votu_mq_reps.fasta). Default "medium". Lower to
# "low"/"not_determined" for high-novelty datasets (e.g. IonTorrent viromes)
# where most contigs are Low-quality/Not-determined.
# (it keeps its own HQ+/>=10kb gate).
VIRAL_MIN_QUALITY      = _PCFG["viral_min_quality"]
VIRAL_MIN_QUALITY_RANK = _PCFG["viral_min_quality_rank"]
VIRAL_KEEP_TIERS       = _PCFG["viral_keep_tiers"]

# Selecting the reads track implies the reads-classify module runs.
READS_CLASSIFY_ENABLED = READS_CLASSIFY_ENABLED or TRACK_READS


# ══════════════════════════════════════════════════════════════════════
#  SAMPLE DISCOVERY
#  SR PE : paired *_R1*/*_R2* or *_1.*/*_2.* FASTQs
#  SR SE : single *.fq.gz / *.fastq.gz (no _R1/_R2 suffix)
#  LR    : single-end *.fastq.gz / *.fq.gz
# ══════════════════════════════════════════════════════════════════════

_PE_PATTERNS = re.compile(r"_R[12]|_[12]\.")

def find_samples(fastq_dir, long_reads=False, single_end=False):
    samples = {}
    fq_dir = Path(fastq_dir).expanduser()
    if long_reads:
        patterns = ["*.fastq.gz", "*.fq.gz", "*.fastq", "*.fq"]
        seen = set()
        for pat in patterns:
            for f in sorted(fq_dir.glob(pat)):
                sample = re.sub(r"\.f(ast)?q(\.gz)?$", "", f.name)
                if sample not in seen:
                    samples[sample] = {"LR": str(f)}
                    seen.add(sample)
    elif single_end:
        seen = set()
        for pat in ["*.fastq.gz", "*.fq.gz"]:
            for f in sorted(fq_dir.glob(pat)):
                if _PE_PATTERNS.search(f.name):
                    continue  # skip R1/R2 files
                sample = re.sub(r"\.f(ast)?q(\.gz)?$", "", f.name)
                if sample not in seen:
                    samples[sample] = {"R1": str(f)}
                    seen.add(sample)
    else:
        seen = set()
        # Support both _R1/_R2 and _1/_2 naming conventions
        for pattern, tag1, tag2 in [
            ("*_R1*.f*q.gz", "_R1", "_R2"),
            ("*_1.f*q.gz",   "_1.", "_2."),
        ]:
            for r1 in sorted(fq_dir.glob(pattern)):
                sample = re.sub(r"_R1.*|_1\.f.*", "", r1.name)
                if sample in seen:
                    continue
                r2_name = re.sub(re.escape(tag1), tag2, r1.name, count=1)
                r2 = fq_dir / r2_name
                if r2.exists():
                    samples[sample] = {"R1": str(r1), "R2": str(r2)}
                    seen.add(sample)
    return samples

SAMPLES = find_samples(FASTQ_DIR, long_reads=LONG_READS, single_end=SINGLE_END)
if not SAMPLES:
    if LONG_READS:
        mode = "long read (single-end)"
    elif SINGLE_END:
        mode = "single-end short read"
    else:
        mode = "paired short read"
    raise ValueError(f"No {mode} FASTQs found in {FASTQ_DIR}")

print(f"[Snakemake] Samples ({'LR' if LONG_READS else 'SR'}): {list(SAMPLES.keys())}")

# Pre-create logs/ directories — Snakemake creates output dirs automatically
# but NOT log dirs, which causes redirect failures on first run.
_outdir_expanded = Path(OUTDIR).expanduser()
for _s in SAMPLES:
    (_outdir_expanded / _s / "logs").mkdir(parents=True, exist_ok=True)

# ── Co-assembly / co-binning GROUPS (Plan 2) ──────────────────────────
from coassembly_groups import parse_groups

COASSEMBLY_METADATA = _expand(config.get("coassembly", {}).get("metadata", "")) \
    if config.get("coassembly", {}).get("metadata", "") else ""

# GROUPS is only used by the co-assembly rules (per-group). Multi-split uses ALL
# SAMPLES directly, so it needs no grouping/metadata — build GROUPS only for co-assembly.
GROUPS = {}
if COASSEMBLY_ENABLED:
    GROUPS = parse_groups(COASSEMBLY_METADATA, list(SAMPLES.keys()), COASSEMBLY_GROUPING)
    print(f"[Snakemake] Co-assembly groups: {({g: len(s) for g, s in GROUPS.items()})}")


# ══════════════════════════════════════════════════════════════════════
#  MODULE INCLUDES
#  Order matters only within a module — cross-module rule references
#  (rules.X.output.Y) work because all modules are loaded before execution.
# ══════════════════════════════════════════════════════════════════════

include: "rules/qc.smk"
include: "rules/host_removal.smk"
include: "rules/assembly.smk"
include: "rules/quast.smk"
include: "rules/viral_detection.smk"
include: "rules/mapping.smk"
include: "rules/cobra.smk"
include: "rules/votu_catalog.smk"
include: "rules/viral_binning.smk"
include: "rules/prok_binning.smk"
# Depois do prok_binning: o catalogo consome os bins e o CheckM2 dele.
include: "rules/mag_catalog.smk"
include: "rules/taxonomy.smk"
include: "rules/host_prediction.smk"
include: "rules/abundance.smk"
include: "rules/annotation.smk"
include: "rules/defense_amr.smk"
include: "rules/finalize.smk"
include: "rules/report.smk"
include: "rules/reads_classify.smk"
include: "rules/coassembly.smk"


# ══════════════════════════════════════════════════════════════════════
#  RULEORDER — must live in the main Snakefile so Snakemake resolves
#  ambiguity between minimap2_lr and bwa_mem before building the DAG.
# ══════════════════════════════════════════════════════════════════════

if LONG_READS:
    ruleorder: minimap2_lr > bwa_mem
    ruleorder: samtools_sort_lr > samtools_sort


# ══════════════════════════════════════════════════════════════════════
#  TARGET BUILDERS — cada track contribui sua fatia de alvos ao rule all.
#  Includes permanecem; só o rule all decide o que efetivamente roda.
# ══════════════════════════════════════════════════════════════════════

def _t_foundation():
    t = []
    if not LONG_READS:
        t += expand(f"{OUTDIR}/{{sample}}/qc_raw/done.txt", sample=SAMPLES)
    else:
        t += expand(f"{OUTDIR}/{{sample}}/qc_lr/nanoplot_done.txt", sample=SAMPLES)
    if TRACK_VIRAL or TRACK_PROK:
        # The hub is the assembly itself since (d) -- no merge, no dedup.
        t += [_contigs_path(s) for s in SAMPLES]
        t += expand(f"{OUTDIR}/{{sample}}/quast/report.tsv", sample=SAMPLES)
        if LONG_READS:
            # done sentinel of the single LR assembler (merge_lr is gone)
            t += expand(
                f"{OUTDIR}/{{sample}}/assembly/lr/medaka_done.txt"
                if LR_TECH == "ont"
                else f"{OUTDIR}/{{sample}}/assembly/lr/metaMDBG/done.txt",
                sample=SAMPLES,
            )
        # mapping/depth feeds both viral (vRhyme coverage) and prok (binning depth)
        t += expand(f"{OUTDIR}/{{sample}}/mapping/{{sample}}.sorted.bam", sample=SAMPLES)
        t += expand(f"{OUTDIR}/{{sample}}/mapping/{{sample}}_depth.txt", sample=SAMPLES)
        if not LONG_READS:
            t += expand(f"{OUTDIR}/{{sample}}/mapping/bwa_mem_done.txt", sample=SAMPLES)
    return t


def _t_reads():
    # reads track roda se explicitamente selecionada OU se reads_classify legado ligado
    if not (TRACK_READS or READS_CLASSIFY_ENABLED):
        return []
    return [
        f"{OUTDIR}/reads_classify/reads_classify_done.txt",
        f"{OUTDIR}/final/reads_classify/done.txt",
    ]


def _t_viral():
    if not TRACK_VIRAL:
        return []
    t = []
    t += expand(f"{OUTDIR}/{{sample}}/viral/virsorter2/final-viral-combined.fa", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/viral/genomad/done.txt", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/viral/consensus/{{sample}}_viral_consensus.fasta", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/viral/consensus/{{sample}}_tool_support.tsv", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/viral/checkv/quality_summary.tsv", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/bins/vrhyme/done.txt", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/viral/checkv_vrhyme/quality_summary.tsv", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/viral/consensus/{{sample}}_viral_nonredundant.fasta", sample=SAMPLES)
    # Catalogo global de vOTU: estagio obrigatorio desde 2026-08-18.
    # A flag votu_catalog_enabled existia para quando o clustering por
    # amostra ainda era a alternativa; ele foi removido, e a flag so
    # gateava estes alvos -- nunca as regras, que os demais consumidores
    # puxavam de volta de qualquer jeito.
    t.append(f"{OUTDIR}/final/votu_catalog/done.txt")
    t.append(f"{OUTDIR}/votu_catalog/vOTU_clusters.tsv")
    t.append(f"{OUTDIR}/votu_catalog/catalog_all_reps.fasta")
    t.append(f"{OUTDIR}/votu_catalog/done.txt")
    t.append(f"{OUTDIR}/votu_catalog/presence_matrix.tsv")
    t.append(f"{OUTDIR}/votu_catalog/votu_abundance_matrix.tsv")
    t.append(f"{OUTDIR}/votu_catalog/matrices_done.txt")
    t.append(f"{OUTDIR}/votu_catalog/bacphlip/votu_lifestyle.tsv")
    t.append(f"{OUTDIR}/votu_catalog/bacphlip/done.txt")
    t.append(f"{OUTDIR}/votu_catalog/taxonomy/viral_taxonomy_merged.tsv")
    t.append(f"{OUTDIR}/votu_catalog/taxonomy/taxonomy_done.txt")
    if USE_EGGNOG_VIRAL:
        t.append(f"{OUTDIR}/votu_catalog/eggnog_viral/putative_amgs.tsv")
        t.append(f"{OUTDIR}/votu_catalog/eggnog_viral/done.txt")
    # pharokka/phold: moved to the global catalog on 2026-08-18 (second half
    # of "(h)", docs/ROADMAP_SIMPLIFICACAO.md). Os genome maps foram removidos
    # em 2026-08-19.
    t.append(f"{OUTDIR}/votu_catalog/annotation/pharokka/done.txt")
    t.append(f"{OUTDIR}/votu_catalog/annotation/phold/done.txt")
    # defensefinder_viral/dbapis_viral: moved to the global catalog on
    # 2026-08-18 too (same move, same reasoning) -- no longer per-sample
    # or per-group, see rules/votu_catalog.smk.
    if DEFENSE_AMR_VIRAL_ENABLED:
        t.append(f"{OUTDIR}/votu_catalog/defensefinder/done.txt")
        t.append(f"{OUTDIR}/votu_catalog/dbapis/done.txt")
    t += expand(f"{OUTDIR}/{{sample}}/viral/votu/{{sample}}_vOTU_table.tsv", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/viral/votu/{{sample}}_vOTU_abundance.tsv", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/viral/taxonomy/taxonomy_done.txt", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/abundance/viral_abundance.tsv", sample=SAMPLES)
    return t


def _t_prok():
    if not TRACK_PROK:
        return []
    t = []
    t += expand(f"{OUTDIR}/{{sample}}/bins/metabat2/done.txt", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/bins/semibin2/done.txt", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/bins/binette/done.txt", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/bins/checkm2/quality_report.tsv", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/bins/gtdbtk/done.txt", sample=SAMPLES)
    if GUNC_ENABLED:
        t += expand(f"{OUTDIR}/{{sample}}/bins/gunc/GUNC.progenomes_2.1.maxCSS_level.tsv", sample=SAMPLES)
    # A desreplicacao virou GLOBAL em 2026-08-19 (rules/mag_catalog.smk): um
    # galah so, sobre o pool namespaced de todas as amostras e grupos. O
    # antigo alvo por amostra (bins/derep/done.txt) sumiu junto com a regra.
    t.append(f"{OUTDIR}/mag_catalog/derep_done.txt")
    t.append(f"{OUTDIR}/mag_catalog/mag_membership.tsv")
    t.append(f"{OUTDIR}/mag_catalog/gtdbtk/done.txt")
    t += expand(f"{OUTDIR}/{{sample}}/bins/mmseqs_taxonomy_prok/done.txt", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/bins/proteins/done.txt", sample=SAMPLES)
    if DEFENSE_AMR_ENABLED:
        t += expand(f"{OUTDIR}/{{sample}}/bins/defensefinder/done.txt", sample=SAMPLES)
        t += expand(f"{OUTDIR}/{{sample}}/bins/amrfinderplus/done.txt", sample=SAMPLES)
        t += expand(f"{OUTDIR}/{{sample}}/bins/rgi/done.txt", sample=SAMPLES)
        t += expand(f"{OUTDIR}/{{sample}}/bins/deeparg/done.txt", sample=SAMPLES)
        if AMR_CONSENSUS_ENABLED:
            t += expand(f"{OUTDIR}/{{sample}}/bins/amr_consensus/done.txt", sample=SAMPLES)
    if ABRICATE_ENABLED:
        t += expand(f"{OUTDIR}/{{sample}}/bins/abricate/done.txt", sample=SAMPLES)
    if ARGNORM_ENABLED:
        t += expand(f"{OUTDIR}/{{sample}}/bins/argnorm/done.txt", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/abundance/prok_abundance.tsv", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/annotation/bakta/done.txt", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/annotation/eggnog/done.txt", sample=SAMPLES)
    t += expand(f"{OUTDIR}/{{sample}}/annotation/kegg_decoder/done.txt", sample=SAMPLES)
    return t


def _t_integration():
    if not INTEGRATION_ENABLED:
        return []
    return expand(f"{OUTDIR}/{{sample}}/viral/phist/done.txt", sample=SAMPLES)


def _t_coassembly():
    # Co-assembly track (Plan 2) + co-assembly viral track (Plan 3).
    # Co-binning is short-read only; viral works for both SR and LR.
    #  short reads + binning → group MAGs (CheckM2 + GTDB per group)
    #  viral enabled → group vOTUs (CheckV + vOTU reps + taxonomy per group)
    #  neither consumer active → co-assembled contigs only (fallback)
    t = []
    if COASSEMBLY_ENABLED:
        produced = False
        if COASSEMBLY_BINNING and not LONG_READS:
            for g in GROUPS:
                t.append(f"{OUTDIR}/coassembly/{g}/gtdbtk/done.txt")
                t.append(f"{OUTDIR}/coassembly/{g}/checkm2/quality_report.tsv")
                # Group prok functional layer (Plan 5), gated like per-sample _t_prok
                if GUNC_ENABLED:
                    t.append(f"{OUTDIR}/coassembly/{g}/bins/gunc/GUNC.progenomes_2.1.maxCSS_level.tsv")
                if DEFENSE_AMR_ENABLED:
                    t.append(f"{OUTDIR}/coassembly/{g}/bins/defensefinder/done.txt")
                    t.append(f"{OUTDIR}/coassembly/{g}/bins/amrfinderplus/done.txt")
                    t.append(f"{OUTDIR}/coassembly/{g}/bins/rgi/done.txt")
                    t.append(f"{OUTDIR}/coassembly/{g}/bins/deeparg/done.txt")
                    if AMR_CONSENSUS_ENABLED:
                        t.append(f"{OUTDIR}/coassembly/{g}/bins/amr_consensus/done.txt")
                if ABRICATE_ENABLED:
                    t.append(f"{OUTDIR}/coassembly/{g}/bins/abricate/done.txt")
                if ARGNORM_ENABLED:
                    t.append(f"{OUTDIR}/coassembly/{g}/bins/argnorm/done.txt")
                t.append(f"{OUTDIR}/coassembly/{g}/annotation/bakta/done.txt")
                t.append(f"{OUTDIR}/coassembly/{g}/annotation/eggnog/done.txt")
                t.append(f"{OUTDIR}/coassembly/{g}/annotation/kegg_decoder/done.txt")
            produced = True
        if COASSEMBLY_VIRAL:
            for g in GROUPS:
                t.append(f"{OUTDIR}/coassembly/{g}/viral/taxonomy/taxonomy_done.txt")
                t.append(f"{OUTDIR}/coassembly/{g}/viral/checkv/quality_summary.tsv")
                t.append(f"{OUTDIR}/coassembly/{g}/viral/votu/votu_all_reps.fasta")
                # pharokka/phold/defensefinder_viral/dbapis_viral: moved to
                # the global catalog on 2026-08-18 (second half of "(h)")
                # -- the catalog already includes every coassembly group as
                # a source, so there is no per-group target here any more;
                # see the global votu_catalog/{annotation/{pharokka,phold},
                # defensefinder,dbapis} targets in _t_viral() above.
                # vRhyme vMAGs + PHIST host prediction need coverage/MAGs → short reads only
                if not LONG_READS:
                    t.append(f"{OUTDIR}/coassembly/{g}/viral/checkv_vrhyme/quality_summary.tsv")
                    if COASSEMBLY_BINNING:
                        t.append(f"{OUTDIR}/coassembly/{g}/viral/phist/done.txt")
            produced = True
        if not produced:
            for g in GROUPS:
                t.append(f"{OUTDIR}/coassembly/{g}/contigs.fa")
        # Clean per-group final/ tree (mirrors per-sample organize_outputs).
        if produced:
            for g in GROUPS:
                t.append(f"{OUTDIR}/coassembly/{g}/final/done.txt")
    if COBINNING_MULTISPLIT and not LONG_READS:
        t.append(f"{OUTDIR}/coassembly/multisplit/gtdbtk/done.txt")
        t.append(f"{OUTDIR}/coassembly/multisplit/checkm2/quality_report.tsv")
    return t


def _t_report():
    t = [
        expand(f"{OUTDIR}/{{sample}}/final/done.txt", sample=SAMPLES),
        f"{OUTDIR}/benchmarks/pipeline_timing_summary.tsv",
        f"{OUTDIR}/report.html",
    ]
    if TRACK_VIRAL or TRACK_PROK:
        t.append(f"{OUTDIR}/diversity/diversity_done.txt")
    # MultiQC aggregates assembly QC (QUAST) + fastp — only meaningful when an
    # assembly-based track ran; otherwise it drags the whole assembly into a
    # reads-only DAG.
    if not LONG_READS and (TRACK_VIRAL or TRACK_PROK):
        t.append(f"{OUTDIR}/multiqc_report/multiqc_report.html")
    # flatten (expand returns lists)
    flat = []
    for x in t:
        flat += x if isinstance(x, list) else [x]
    return flat


# ══════════════════════════════════════════════════════════════════════
#  RULE ALL — final targets
# ══════════════════════════════════════════════════════════════════════

rule all:
    input:
        *_t_foundation(),
        *_t_reads(),
        *_t_viral(),
        *_t_prok(),
        *_t_integration(),
        *_t_coassembly(),
        *_t_report(),
