# Dockerfile.genome-map
# Custom image for VAPOR circular genome map rules.
# Combines pycirclize + matplotlib + biopython in a single container.
#
# Build and push to GHCR:
#   docker build -f docker/Dockerfile.genome-map -t lymff/vapor-genome-map:1.0 .
#   docker push lymff/vapor-genome-map:1.0
#
# Versions must match envs/env_annotation.yaml.

FROM python:3.12-slim

LABEL org.opencontainers.image.source="https://github.com/LymF/vapor"
LABEL org.opencontainers.image.description="VAPOR genome map tools: pycirclize + matplotlib + biopython"
LABEL org.opencontainers.image.version="1.0"

RUN pip install --no-cache-dir \
        pycirclize==1.10.1 \
        matplotlib==3.10.0 \
        biopython==1.85

CMD ["/bin/bash"]
