#!/usr/bin/env python3
"""
prepare_mmseqs_taxdb.py — Build an MMseqs2 seqTaxDB (custom taxonomy,
LCA-capable) from a protein FASTA + a lineage file. Same multi-format
pattern as prepare_diamond_db.py (--format img/ncbi/...), but for MMseqs2's
`taxonomy` module instead of Diamond.

Why: best-hit + majority-vote approaches (diamond_custom_prok,
diamond_custom_viral) are prone to "spurious specificity" -- a single
highly-conserved or HGT-acquired region can give a confident species-level
best hit even when the organism is actually novel/divergent (documented for
best-hit-only methods, von Meijenfeldt et al. 2019, the CAT/BAT paper).
`mmseqs taxonomy` computes a real lowest-common-ancestor per query across
all its hits instead, resolving to the correct (coarser) rank when hits
disagree, rather than committing to one best-hit's call.

Supports input formats:
  --format img      : IMG NR (hash headers ">HASH length TAXON_OID:GENE_OID"
                       + taxonOId2Taxonomy.tsv semicolon lineages). Used for
                       prokaryote bins (rule mmseqs_taxonomy_prok).
  --format inphared : INPHARED (">{Accession}_{n}" headers + *_data.tsv
                       Realm/Kingdom/Phylum/Class/Order/Family/Sub-family/
                       Genus columns). Used for viral contigs (rule
                       mmseqs_taxonomy_viral) -- this is the pipeline's only
                       INPHARED-based taxonomy source (an earlier
                       Diamond/INPHARED rule was removed 2026-06-22).
  --format imgvr    : IMG/VR (headers ">{UVIG}|{Taxon_oid}|{rest}" + the
                       *_Sequence_information*.tsv "Taxonomic classification"
                       column, rank-prefixed semicolon lineage e.g.
                       "r__Realm;k__Kingdom;p__Phylum;c__Class;o__Order;
                       f__Family;sf__Subfamily;g__Genus" -- generated by
                       geNomad inside IMG/VR itself, confirmed against a real
                       IMG/VR 2022-12-19 export). Used for viral contigs
                       (rule mmseqs_taxonomy_custom_viral) -- replaced an
                       earlier Diamond-based diamond_custom_viral rule
                       (removed 2026-06-23).
  --format ncbi     : NCBI RefSeq/GenBank (">accession.version description"
                       headers + a TSV with accession + domain/phylum/class/
                       order/family/genus/organism columns -- same
                       convention as prepare_diamond_db.py's --format ncbi).

Each format is just a different (header-parsing, lineage-loading) pair
feeding the same generic taxdump-building/mapping/mmseqs pipeline -- they
are NOT interchangeable (a FASTA in IMG format won't parse correctly with
--format inphared or vice versa).

nodes.dmp/names.dmp use the minimal custom-taxonomy format MMseqs2 itself
documents for non-NCBI taxonomies (confirmed against a real working
example, GTDB-style conversion: github.com/soedinglab/MMseqs2/issues/976):
    nodes.dmp: "{taxid}\t|\t{parent_taxid}\t|\t{rank}\t|\t-\t|"
    names.dmp: "{taxid}\t|\t{name}\t|\t-\t|\tscientific name\t|"
merged.dmp/delnodes.dmp are written empty -- `mmseqs createtaxdb`'s
createbintaxonomy step requires them to exist even for a from-scratch
custom taxonomy with no merged/deleted taxon IDs to report (confirmed live
on litrp4: "Input .../merged.dmp does not exist").

Two-pass design, memory bounded by the number of GENOMES (the lineage file,
tens-hundreds of thousands of rows), not the number of PROTEINS (the raw
FASTA can have hundreds of millions of headers) -- pass 1 builds the small
key -> leaf_taxid dict from the lineage file; pass 2 streams the FASTA
headers and writes the mapping file line by line, never holding all
protein IDs in memory at once.

Usage:
  # IMG NR (prokaryote bins)
  python3 prepare_mmseqs_taxdb.py \\
      --faa img_unrestricted_isolates_nr.faa --format img \\
      --img-tax taxonOId2Taxonomy.tsv \\
      --out /path/to/img_nr_mmseqs --threads 32

  # INPHARED (viral contigs)
  python3 prepare_mmseqs_taxdb.py \\
      --faa 14Apr2025_vConTACT2_proteins.faa --format inphared \\
      --inphared-tax 14Apr2025_data.tsv \\
      --out /path/to/inphared/inphared_mmseqs_taxdb --threads 32

  # NCBI RefSeq/GenBank
  python3 prepare_mmseqs_taxdb.py \\
      --faa viral.1.protein.faa --format ncbi \\
      --ncbi-tax taxonomy.tsv \\
      --out /path/to/refseq_viral_mmseqs --threads 32

  # IMG/VR (viral contigs, custom DB)
  python3 prepare_mmseqs_taxdb.py \\
      --faa IMGVR_all_proteins-high_confidence.faa --format imgvr \\
      --imgvr-tax IMGVR_all_Sequence_information-high_confidence.tsv \\
      --out /path/to/imgvr_mmseqs --threads 32
"""
import argparse, csv, glob, os, subprocess, sys

FORMAT_RANKS = {
    'img':      ['domain', 'phylum', 'class', 'order', 'family', 'genus', 'species', 'strain'],
    'ncbi':     ['domain', 'phylum', 'class', 'order', 'family', 'genus', 'species', 'strain'],
    'inphared': ['realm', 'kingdom', 'phylum', 'class', 'order', 'family', 'subfamily', 'genus'],
    'imgvr':    ['realm', 'kingdom', 'phylum', 'class', 'order', 'family', 'subfamily', 'genus'],
}
INPHARED_TAX_COLUMNS = ['Realm', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Sub-family', 'Genus']
NCBI_TAX_COLUMNS     = ['domain', 'phylum', 'class', 'order', 'family', 'genus', 'organism']
# IMG/VR's "Taxonomic classification" column uses rank-letter prefixes
# (e.g. "r__Monodnaviria;k__Loebvirae;p__...;;;" -- confirmed against a real
# IMG/VR 2022-12-19 high-confidence export) rather than fixed comma position,
# so gaps are identified by prefix, not by counting empty fields.
IMGVR_RANK_PREFIXES = {'r': 0, 'k': 1, 'p': 2, 'c': 3, 'o': 4, 'f': 5, 'sf': 6, 'g': 7}


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--faa', required=True, help='Input protein FASTA (format-specific headers)')
    p.add_argument('--format', required=True, choices=['img', 'ncbi', 'inphared', 'imgvr'],
                   help='Input format (see usage examples)')
    p.add_argument('--img-tax', help='IMG taxonOId2Taxonomy.tsv (required for --format img)')
    p.add_argument('--inphared-tax', help='INPHARED *_data.tsv (required for --format inphared)')
    p.add_argument('--ncbi-tax', help='NCBI accession+lineage TSV (required for --format ncbi)')
    p.add_argument('--imgvr-tax', help='IMG/VR *_Sequence_information*.tsv (required for --format imgvr)')
    p.add_argument('--out', required=True, help='Output dir for the seqTaxDB + taxdump files')
    p.add_argument('--threads', type=int, default=16)
    return p.parse_args()


# ── Lineage loaders: format-specific input -> {key: [non-empty rank names in order]} ──

def load_img_lineages(img_tax_path):
    """IMG taxonOId2Taxonomy.tsv: 'taxon_oid\\tDomain;Phylum;Class;...'"""
    lineages = {}
    with open(img_tax_path) as f:
        for line in f:
            parts = line.rstrip('\n').split('\t')
            if len(parts) < 2:
                continue
            taxon_oid = parts[0].strip()
            names = [x.strip() for x in parts[1].split(';') if x.strip()]
            if names:
                lineages[taxon_oid] = names
    return lineages


def load_inphared_lineages(inphared_tax_path):
    """INPHARED *_data.tsv: named columns, gaps in the middle are skipped
    rather than breaking the chain (common in INPHARED)."""
    lineages = {}
    with open(inphared_tax_path) as f:
        for row in csv.DictReader(f, delimiter='\t'):
            acc = row.get('Accession', '').strip()
            if not acc:
                continue
            names = [row.get(col, '').strip() for col in INPHARED_TAX_COLUMNS]
            names = [x for x in names if x]
            if names:
                lineages[acc] = names
    return lineages


def load_ncbi_lineages(ncbi_tax_path):
    """Generic NCBI-style lineage TSV, same column convention as
    prepare_diamond_db.py's --format ncbi (accession + domain/phylum/class/
    order/family/genus/organism, case-insensitive column names)."""
    lineages = {}
    with open(ncbi_tax_path) as f:
        for row in csv.DictReader(f, delimiter='\t'):
            acc = (row.get('accession', '') or row.get('Accession', '')).strip()
            if not acc:
                continue
            names = []
            for col in NCBI_TAX_COLUMNS:
                val = (row.get(col, '') or row.get(col.capitalize(), '')).strip()
                names.append(val)
            names = [x for x in names if x]
            if names:
                lineages[acc] = names
    return lineages


def load_imgvr_lineages(imgvr_tax_path):
    """IMG/VR *_Sequence_information*.tsv: 'UVIG' join key + 'Taxonomic
    classification' column (rank-prefixed, e.g. 'r__X;k__Y;p__Z;;;'). Gaps
    are identified by the rank-letter prefix, not by position, since a
    missing middle rank still leaves later semicolons in place."""
    lineages = {}
    with open(imgvr_tax_path) as f:
        for row in csv.DictReader(f, delimiter='\t'):
            uvig = row.get('UVIG', '').strip()
            if not uvig:
                continue
            tax_str = row.get('Taxonomic classification', '').strip()
            if not tax_str:
                continue
            by_idx = {}
            for tok in tax_str.split(';'):
                tok = tok.strip()
                if not tok or '__' not in tok:
                    continue
                prefix, name = tok.split('__', 1)
                idx = IMGVR_RANK_PREFIXES.get(prefix.strip())
                if idx is not None and name.strip():
                    by_idx[idx] = name.strip()
            names = [by_idx[i] for i in sorted(by_idx)]
            if names:
                lineages[uvig] = names
    return lineages


LINEAGE_LOADERS = {'img': load_img_lineages, 'ncbi': load_ncbi_lineages,
                   'inphared': load_inphared_lineages, 'imgvr': load_imgvr_lineages}


# ── Protein header parsers: FASTA -> yields (protein_id, lookup_key) ──

def iter_proteins_img(faa_path):
    """Headers: '>HASH length TAXON_OID:GENE_OID'"""
    with open(faa_path) as f:
        for line in f:
            if not line.startswith('>'):
                continue
            parts = line[1:].split()
            if len(parts) >= 3:
                yield parts[0], parts[2].split(':')[0]


def iter_proteins_inphared(faa_path):
    """Headers: '>{Accession}_{n}' -- strip trailing _n to get the accession."""
    with open(faa_path) as f:
        for line in f:
            if not line.startswith('>'):
                continue
            protein_id = line[1:].split()[0]
            acc = "_".join(protein_id.split("_")[:-1]) or protein_id
            yield protein_id, acc


def iter_proteins_ncbi(faa_path):
    """Headers: '>accession.version description' -- yields the versioned
    accession; write_mapping() falls back to the unversioned form."""
    with open(faa_path) as f:
        for line in f:
            if not line.startswith('>'):
                continue
            protein_id = line[1:].split()[0]
            yield protein_id, protein_id


def iter_proteins_imgvr(faa_path):
    """Headers: '>{UVIG}|{Taxon_oid}|{rest}' -- the UVIG (first field) is the
    join key against the Sequence_information TSV's 'UVIG' column. Multiple
    proteins from the same scaffold legitimately share the same UVIG (and
    therefore the same taxonomy) -- that's correct, not a collision."""
    with open(faa_path) as f:
        for line in f:
            if not line.startswith('>'):
                continue
            protein_id = line[1:].split()[0]
            uvig = protein_id.split('|')[0]
            yield protein_id, uvig


PROTEIN_ITERATORS = {'img': iter_proteins_img, 'ncbi': iter_proteins_ncbi,
                      'inphared': iter_proteins_inphared, 'imgvr': iter_proteins_imgvr}


# ── Generic taxdump build + mapping (shared across all formats) ──

def build_taxdump(lineages, ranks, taxdump_dir):
    """Build nodes.dmp/names.dmp/merged.dmp/delnodes.dmp from
    {key: [rank0_name, rank1_name, ...]}. Returns {key: leaf_taxid}."""
    os.makedirs(taxdump_dir, exist_ok=True)
    nodes_path = os.path.join(taxdump_dir, 'nodes.dmp')
    names_path = os.path.join(taxdump_dir, 'names.dmp')
    open(os.path.join(taxdump_dir, 'merged.dmp'), 'w').close()
    open(os.path.join(taxdump_dir, 'delnodes.dmp'), 'w').close()

    node_id = {(): 1}   # path-tuple (ancestor names + this name) -> synthetic taxid
    next_id = 2
    key_to_leaf = {}

    with open(nodes_path, 'w') as nf, open(names_path, 'w') as mf:
        nf.write("1\t|\t1\t|\tno rank\t|\t-\t|\n")
        mf.write("1\t|\troot\t|\t-\t|\tscientific name\t|\n")

        for key, lineage in lineages.items():
            path = ()
            parent_id = leaf_id = 1
            for depth, name in enumerate(lineage):
                path = path + (name,)
                existing = node_id.get(path)
                if existing is not None:
                    parent_id = leaf_id = existing
                    continue
                this_id = next_id
                next_id += 1
                node_id[path] = this_id
                rank = ranks[depth] if depth < len(ranks) else 'no rank'
                nf.write(f"{this_id}\t|\t{parent_id}\t|\t{rank}\t|\t-\t|\n")
                mf.write(f"{this_id}\t|\t{name}\t|\t-\t|\tscientific name\t|\n")
                parent_id = leaf_id = this_id
            key_to_leaf[key] = leaf_id

    print(f"[prepare_mmseqs_taxdb] {next_id - 1:,} taxonomy nodes written, "
          f"{len(key_to_leaf):,} genomes mapped")
    return key_to_leaf


def write_mapping(faa_path, fmt, key_to_leaf, mapping_path):
    """Stream the FASTA headers, write '{protein_id}\\t{leaf_taxid}' per
    protein -- never holds all protein IDs in memory at once. For --format
    ncbi, falls back to the unversioned accession if the versioned one
    isn't in the lineage map."""
    n_written = n_skipped = 0
    with open(mapping_path, 'w') as out:
        for protein_id, key in PROTEIN_ITERATORS[fmt](faa_path):
            taxid = key_to_leaf.get(key)
            if taxid is None and fmt == 'ncbi':
                taxid = key_to_leaf.get(key.split('.')[0])
            if taxid is None:
                n_skipped += 1
                continue
            out.write(f"{protein_id}\t{taxid}\n")
            n_written += 1
    print(f"[prepare_mmseqs_taxdb] mapping written: {n_written:,} proteins mapped, "
          f"{n_skipped:,} skipped (no taxonomy entry for their lookup key)")
    return n_written


def build(faa_path, fmt, tax_path, out_dir, threads):
    os.makedirs(out_dir, exist_ok=True)
    taxdump_dir  = os.path.join(out_dir, 'taxdump')
    mapping_path = os.path.join(out_dir, 'mapping.tsv')
    seqdb_path   = os.path.join(out_dir, 'seqTaxDB')
    tmp_dir      = os.path.join(out_dir, 'tmp')

    lineages = LINEAGE_LOADERS[fmt](tax_path)
    key_to_leaf = build_taxdump(lineages, FORMAT_RANKS[fmt], taxdump_dir)
    n_mapped = write_mapping(faa_path, fmt, key_to_leaf, mapping_path)
    if n_mapped == 0:
        print(f"[prepare_mmseqs_taxdb] ERROR: no proteins mapped to a taxonomy node -- "
              f"check --faa header format matches --format {fmt}", file=sys.stderr)
        sys.exit(1)

    # Re-running after a partial failure (e.g. createtaxdb died partway
    # through) leaves stale tmp/seqTaxDB_taxonomy* state that mmseqs refuses
    # to overwrite -- clean it first so this script is safe to just re-run.
    subprocess.run(['rm', '-rf', tmp_dir] + glob.glob(seqdb_path + '_taxonomy*'))

    if os.path.exists(seqdb_path + '.dbtype'):
        print(f"[prepare_mmseqs_taxdb] {seqdb_path} already exists -- "
              "skipping mmseqs createdb (delete it to force a rebuild)")
    else:
        print("[prepare_mmseqs_taxdb] Building MMseqs2 sequence DB (mmseqs createdb)...")
        subprocess.run(['mmseqs', 'createdb', faa_path, seqdb_path], check=True)

    print("[prepare_mmseqs_taxdb] Running mmseqs createtaxdb "
          "(can take a while for large protein sets)...")
    subprocess.run(['mmseqs', 'createtaxdb', seqdb_path, tmp_dir,
                     '--ncbi-tax-dump', taxdump_dir,
                     '--tax-mapping-file', mapping_path,
                     '--threads', str(threads)], check=True)
    return seqdb_path


def main():
    args = parse_args()
    tax_path = {'img': args.img_tax, 'ncbi': args.ncbi_tax,
                'inphared': args.inphared_tax, 'imgvr': args.imgvr_tax}[args.format]
    flag = {'img': '--img-tax', 'ncbi': '--ncbi-tax',
             'inphared': '--inphared-tax', 'imgvr': '--imgvr-tax'}[args.format]
    if not tax_path:
        print(f"ERROR: {flag} required for --format {args.format}", file=sys.stderr)
        sys.exit(1)

    seqdb_path = build(args.faa, args.format, tax_path, args.out, args.threads)

    print(f"\n[prepare_mmseqs_taxdb] Done!")
    print(f"  seqTaxDB: {seqdb_path}")
    if args.format == 'img':
        print(f"\nAdd to config.yaml:")
        print(f"  custom_prok_mmseqs_db: \"{seqdb_path}\"")
    elif args.format == 'inphared':
        print(f"\nUsed automatically by rule mmseqs_taxonomy_viral if --out matches "
              f"$INPHARED_DB/inphared_mmseqs_taxdb (see INSTALL.md).")
    elif args.format == 'imgvr':
        print(f"\nAdd to config.yaml:")
        print(f"  custom_viral_mmseqs_db: \"{seqdb_path}\"")


if __name__ == '__main__':
    main()
