#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────
# run_phables_standalone.sh — test Phables outside the Snakemake pipeline
#
# Phables (Mallawaarachchi et al. 2023) resolves phage genomes from the
# metaSPAdes assembly graph using flow decomposition. It expects a directory
# containing the metaSPAdes outputs (FASTA + GFA + paths) and a directory
# with the input read pairs.
#
# Output:
#   results-teste/{sample}/viral/phables_standalone/
#
# Usage:
#   bash scripts/test/run_phables_standalone.sh --sample SAMPLE [--results-dir results-teste] [--fastq-dir fastq]
#   bash scripts/test/run_phables_standalone.sh --sample SAMPLE --use-conda
# ──────────────────────────────────────────────────────────────────────
set -euo pipefail

SAMPLE=""
RESULTS_DIR="results-teste"
FASTQ_DIR=""
THREADS=16
USE_CONDA=0

while [ $# -gt 0 ]; do
    case "$1" in
        --sample)       SAMPLE="$2"; shift 2 ;;
        --results-dir)  RESULTS_DIR="$2"; shift 2 ;;
        --fastq-dir)    FASTQ_DIR="$2"; shift 2 ;;
        --threads)      THREADS="$2"; shift 2 ;;
        --use-conda)    USE_CONDA=1; shift ;;
        -h|--help)
            sed -n '2,17p' "$0"; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; exit 2 ;;
    esac
done

if [ -z "$SAMPLE" ]; then
    echo "ERROR: --sample required" >&2; exit 2
fi

RESULTS_DIR="$(realpath "$RESULTS_DIR")"
SAMPLE_DIR="$RESULTS_DIR/$SAMPLE"
ASM_DIR="$SAMPLE_DIR/assembly/metaspades"
OUT="$SAMPLE_DIR/viral/phables_standalone"

if [ ! -s "$ASM_DIR/assembly_graph_with_scaffolds.gfa" ]; then
    echo "ERROR: missing metaSPAdes GFA at $ASM_DIR" >&2; exit 1
fi

# Phables wants a directory with read pairs ({sample}_R1/_R2 or _1/_2 .fastq.gz)
if [ -z "$FASTQ_DIR" ]; then
    # default: look in $SAMPLE_DIR/trimmed first, then a sibling `fastq/` next to results
    if [ -d "$SAMPLE_DIR/trimmed" ]; then FASTQ_DIR="$(realpath "$SAMPLE_DIR/trimmed")"
    elif [ -d "$RESULTS_DIR/../fastq" ]; then FASTQ_DIR="$(realpath "$RESULTS_DIR/../fastq")"
    else
        echo "ERROR: cannot find reads — use --fastq-dir <path>" >&2; exit 1
    fi
fi

mkdir -p "$OUT"

# Phables install step (only needed once for a given DB cache directory).
# Inside Docker the DBs live under /root/.phables — we mount a host cache.
PHABLES_DB_CACHE="${PHABLES_DB_CACHE:-$HOME/.phables_db}"
mkdir -p "$PHABLES_DB_CACHE"

if [ "$USE_CONDA" -eq 1 ]; then
    eval "$(conda shell.bash hook)"
    conda activate env_phables   # env not generated by VAPOR — create with `mamba create -n env_phables phables`
    phables install || true
    phables run \
        --input  "$ASM_DIR" \
        --reads  "$FASTQ_DIR" \
        --output "$OUT" \
        --threads "$THREADS"
else
    FASTQ_DIR="$(realpath "$FASTQ_DIR")"
    docker run --rm \
        -v "$RESULTS_DIR:$RESULTS_DIR" \
        -v "$FASTQ_DIR:$FASTQ_DIR" \
        -v "$PHABLES_DB_CACHE:$PHABLES_DB_CACHE" \
        -e "HOME=$PHABLES_DB_CACHE" \
        quay.io/biocontainers/phables:1.5.0--pyhdfd78af_0 \
        bash -c "phables install || true && \
                 phables run \
                     --input  '$ASM_DIR' \
                     --reads  '$FASTQ_DIR' \
                     --output '$OUT' \
                     --threads $THREADS"
fi

echo "──────────────────────────────────────────"
echo "Phables run finished."
echo "Output: $OUT"
ls -la "$OUT" 2>/dev/null | head -20 || true
