# ══════════════════════════════════════════════════════════════════════
# rules/abundance.smk — BLOCK 4b: Abundance Normalisation + Diversity
#
# coverm_viral   — RPKM/TPM per vOTU (viral contig) from BAM
# coverm_prok    — RPKM/TPM per MAG  (Binette bins) from BAM
# compute_diversity — alpha (Shannon, Simpson, Chao1), beta (Bray-Curtis
#                   PCoA), combined viral+prok, Procrustes co-variation
# ══════════════════════════════════════════════════════════════════════


rule coverm_viral:
    """
    CoverM — per-vOTU abundance normalisation from sorted BAM.
    Calculates RPKM, TPM, covered_fraction, and mean depth for each vOTU.
    Input: sorted BAM (already generated by mapping) + viral_nonredundant FASTA.
    Filters output to only the vOTU representative IDs from viral_nonredundant.fasta.
    """
    input:
        bam      = f"{OUTDIR}/{{sample}}/mapping/{{sample}}.sorted.bam",
        viral_nr = rules.viral_nonredundant.output.fasta,
    output:
        tsv = f"{OUTDIR}/{{sample}}/abundance/viral_abundance.tsv",
    log:
        f"{OUTDIR}/{{sample}}/logs/coverm_viral.log"
    benchmark:
        f"{OUTDIR}/{{sample}}/benchmarks/coverm_viral.tsv"
    conda: "../envs/env_coverm.yaml"
    container:  CONTAINERS.get("coverm")
    threads: THREADS
    params:
        method = COVERM_METHOD,
        outdir = f"{OUTDIR}/{{sample}}/abundance",
    shell:
        """
        mkdir -p {params.outdir}
        if [ ! -s {input.viral_nr} ]; then
            echo "[coverm_viral] No viral sequences — writing empty table" | tee {log}
            printf "Contig\\t{wildcards.sample}_{params.method}\n" > {output.tsv}
            exit 0
        fi
        coverm contig \
            --bam-files {input.bam} \
            --min-read-percent-identity 95 \
            --min-read-aligned-length 45 \
            --contig-end-exclusion 75 \
            --methods {params.method} mean covered_fraction \
            --threads {threads} \
            --output-file {output.tsv} \
            > {log} 2>&1

        # Filter to only vOTU IDs (exclude prokaryotic contigs)
        VOTU_IDS={params.outdir}/votu_ids.txt
        grep "^>" {input.viral_nr} | sed 's/^>//' | awk '{{print $1}}' > "$VOTU_IDS"
        HEADER=$(head -1 {output.tsv})
        FILTERED={output.tsv}.filtered
        echo "$HEADER" > "$FILTERED"
        awk 'NR==FNR{{ids[$1]=1; next}} ($1 in ids)' "$VOTU_IDS" {output.tsv} >> "$FILTERED"
        mv "$FILTERED" {output.tsv}
        echo "[coverm_viral] $(( $(wc -l < {output.tsv}) - 1 )) vOTUs in table" | tee -a {log}
        """


rule coverm_prok:
    """
    CoverM — per-MAG abundance normalisation from sorted BAM.
    Calculates RPKM, TPM, covered_fraction, and mean depth per Binette MAG.
    Uses genome-mode: each MAG FASTA = one genome unit.
    """
    input:
        bam        = f"{OUTDIR}/{{sample}}/mapping/{{sample}}.sorted.bam",
        binette    = rules.binette.output.done,
    output:
        tsv = f"{OUTDIR}/{{sample}}/abundance/prok_abundance.tsv",
    log:
        f"{OUTDIR}/{{sample}}/logs/coverm_prok.log"
    benchmark:
        f"{OUTDIR}/{{sample}}/benchmarks/coverm_prok.tsv"
    conda: "../envs/env_coverm.yaml"
    container:  CONTAINERS.get("coverm")
    threads: THREADS
    params:
        method  = COVERM_METHOD,
        bin_dir = f"{OUTDIR}/{{sample}}/bins/binette/final_bins",
        outdir  = f"{OUTDIR}/{{sample}}/abundance",
    shell:
        """
        mkdir -p {params.outdir}
        N_BINS=$(ls {params.bin_dir}/*.fa 2>/dev/null | wc -l)
        if [ "$N_BINS" -eq 0 ]; then
            echo "[coverm_prok] No MAGs — writing empty table" | tee {log}
            printf "Genome\\t{wildcards.sample}_{params.method}\n" > {output.tsv}
            exit 0
        fi
        coverm genome \
            --bam-files {input.bam} \
            --genome-fasta-directory {params.bin_dir} \
            --genome-fasta-extension fa \
            --min-read-percent-identity 95 \
            --min-read-aligned-length 45 \
            --contig-end-exclusion 75 \
            --methods {params.method} mean covered_fraction \
            --threads {threads} \
            --output-file {output.tsv} \
            > {log} 2>&1
        echo "[coverm_prok] $(( $(wc -l < {output.tsv}) - 1 )) MAGs in table" | tee -a {log}
        """


rule compute_diversity:
    """
    Alpha + beta + combined diversity from CoverM abundance matrices.

    Outputs per sample:
      diversity/alpha_diversity.tsv      — Shannon, Simpson, Chao1, Richness per domain
      diversity/beta_pcoord_viral.tsv    — PCoA coordinates (viral, Bray-Curtis)
      diversity/beta_pcoord_prok.tsv     — PCoA coordinates (prokaryotic, Bray-Curtis)
      diversity/beta_pcoord_combined.tsv — PCoA coordinates (viral+prok merged)
      diversity/procrustes_coords.tsv    — Procrustes-aligned viral/prok coords

    NOTE: this rule runs across ALL samples at once (single output directory).
    Triggered only after all per-sample CoverM jobs finish.
    """
    input:
        viral_tables = expand(f"{OUTDIR}/{{sample}}/abundance/viral_abundance.tsv",
                              sample=SAMPLES),
        prok_tables  = expand(f"{OUTDIR}/{{sample}}/abundance/prok_abundance.tsv",
                              sample=SAMPLES),
    output:
        alpha     = f"{OUTDIR}/diversity/alpha_diversity.tsv",
        pcoa_v    = f"{OUTDIR}/diversity/beta_pcoord_viral.tsv",
        pcoa_p    = f"{OUTDIR}/diversity/beta_pcoord_prok.tsv",
        pcoa_c    = f"{OUTDIR}/diversity/beta_pcoord_combined.tsv",
        procrust  = f"{OUTDIR}/diversity/procrustes_coords.tsv",
        done      = f"{OUTDIR}/diversity/diversity_done.txt",
    log:
        f"{OUTDIR}/diversity/compute_diversity.log"
    benchmark:
        f"{OUTDIR}/benchmarks/compute_diversity.tsv"
    conda: "../envs/env_coverm.yaml"
    params:
        outdir  = f"{OUTDIR}/diversity",
        samples = list(SAMPLES.keys()),
        method  = COVERM_METHOD,
    script:
        "../scripts/compute_diversity.py"
